INSERT INTO alcohol
VALUES
       (
        --barcodes, region -Polska, flavour cytryna
        DEFAULT,
        'Krupnik Cytryna',
        'likier',
        NULL,
        'owocowy',
         '',
        TODO,
        30.0,
        'żółty',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Krupnik',
        NULL,
        TODO
        ),
        (
        --flavour - pigwa, barcodes, region - Polska,
        DEFAULT,
        'Barmańska Pigwa',
        'owocowy',
        NULL,
        'smakowa',
        'Inspiracją do powstania Barmańskiej był smak dojrzałych soczystych owoców. Dzięki temu powstała receptura z udziałem soku z pigwy, która sprawia, że Barmańska zaskakuje owocową świeżością. Wyjątkowe walory wynikają z idealnie dobranych proporcji alkoholu i pigwowego smaku. Najlepiej podawać schłodzoną lub z kostkami lodu.',
        TODO,
        21.0,
        'pomarańczowy',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Barmańska',
        NULL,
        TODO
        ),
        (
        --flavour - wiśnia, barcodes, region - Polska
        DEFAULT,
        'Barmańska Wiśnia',
        'likier',
        NULL,
        'owocowy',
        'Barmańska Wiśnia to Polska wódka smakowa. Inspiracją do powstania Barmańskiej był smak dojrzałych, soczystych owoców. Dzięki temu powstała receptura z udziałem soku z wiśni, która sprawia, że Barmańska zaskakuje owocową świeżością. Wyjątkowe walory wynikają również z idealnie dobranych proporcji alkoholu i wiśniowego smaku.Najlepiej podawać schłodzoną lub z kostkami lodu.',
        TODO,
        21.0,
        'czerwony',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Barmańska',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Polska, flavour cytryna
        DEFAULT,
        'Krupnik Cytryna',
        'likier',
        NULL,
        'owocowy',
        'Krupnik cytrynowy to orzeźwiająca, świeża i aromatyczna wódka, łącząca smak dojrzałych, soczystych cytryn, wysokiej klasy spirytus i krystalicznie czystą wodę, czerpaną z własnych studni głębinowych. Jest idealny zarówno do picia w czystej postaci, jak również jako składnik wielu koktajli.',
        TODO,
        30.0,
        'żółty',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Krupnik',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Polska, flavour pigwa
        DEFAULT,
        'Krupnik Pigwa',
        'likier',
        NULL,
        'owocowy',
        'Krupnik pigwowy to szlachetny smak oraz wspaniały zapach zapomnianego owocu pigwy odkryty na nowo. Delikatnie kwaśny i słodki zarazem, owocowy i aromatyczny. Intrygujący i odkrywczy, prawdziwie polski. Dopracowana receptura idealnie skomponowanych składników, potwierdzona badaniem konsumenckim sprawia, że Krupnik pigwowy jest wyjątkowy i godny polecenia. ',
        TODO,
        30.0,
        'pomarańczowy',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Krupnik',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Polska, flavour śliwka
        DEFAULT,
        'Krupnik Śliwka',
        'likier',
        NULL,
        'owocowy',
        'Krupnik śliwkowy to kwintesencja polskiego smaku. Dopracowana receptura, kompozycja najwyższej jakości składników, łącząca w sobie delikatną słodycz dojrzewających w słońcu śliwek, zachwycający aromat, przywodzący na myśl zapachy z dzieciństwa i delikatną moc alkoholu, który wyostrza walory smakowe.',
        TODO,
        30.0,
        'fioletowy',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Krupnik',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Polska, flavour cytryna
        DEFAULT,
        'Lubelska Cytrynówka',
        'likier',
        NULL,
        'owocowy',
        'Lubelska Cytrynówka to Polska wódka smakowa. Orzeźwiający i intensywny smak cytrynówka zawdzięcza idealnie dobranym składnikom i tradycyjnej recepturze. Dzięki marce Lubelska możemy skosztować alkoholu smakującego jak nalewka domowej roboty.',
        TODO,
        30.0,
        'żółty',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Lubelska',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Polska, flavour mango
        DEFAULT,
        'Lubelska Mango',
        'likier',
        NULL,
        'owocowy',
        'Lubelska Mango to orzeźwiający tropikalny smak, który przywodzi na myśl gorące wakacje na odległej wyspie. Dzięki zbalansowanej słodyczy i 30% zawartości alkoholu idealnie sprawdzi się w orzeźwiających shotach jaki i w lekkich drinkach. Lubelska Mango to prawdziwie tropikalny wybór na lato i nie tylko!',
        TODO,
        30.0,
        'pomarańczowy',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Lubelska',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Polska, flavour wiśniowy
        DEFAULT,
        'Lubelska Wiśniówka',
        'likier',
        NULL,
        'owocowy',
        'Wiśniówka Lubelska to wódka o świeżym, soczystym smaku dojrzałych wiśni. Produkowany wyłącznie na bazie naturalnych składników  polski likier, który zaciekawia kolorem i aromatem. Kusi swoim wiśniowym smakiem i zapachem przywodzącym na myśl dojrzewające w południowym słońcu owoce.',
        TODO,
        30.0,
        'czerwony',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Lubelska',
        NULL,
        TODO
        ),
        (
         --barcodes, region - Polska
        DEFAULT,
        'Soplica Cytryna Pigwa',
        'likier',
        NULL,
        'owocowy',
        'Soplica Cytryna Pigwa to Polska nalewka produkowana na bazie nalewów z całych owoców cytryn, ponieważ w takiej formie te owoce oddają pełnię i bogactwo swojego aromatu. Dodatek pigwy  stanowi doskonałe dopełnienie nalewki. To połączenie zapewnia kwaskowaty, rześki smak i niespotykany aromat.',
        TODO,
        28.0,
        'żółty',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Soplica',
        NULL,
        TODO
        ),
         (
         --barcodes, region - Polska
        DEFAULT,
        'Soplica Orzech Laskowy',
        'likier',
        NULL,
        'inny',
        'Soplica Orzech Laskowy to wyjątkowo aromatyczny napój alkoholowy o słodkim smaku orzechów laskowych z polskich lasów. Receptury alkoholi Soplica zostały opracowane wiele lat temu i obejmują wyłącznie najlepsze, naturalne składniki.',
        TODO,
        28.0,
        'brązowy',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Soplica',
        NULL,
        TODO
        ),
       (
         --5900471006448, region - Polska
        DEFAULT,
        'Soplica Cytrynowa z nutą miodu',
        'likier',
        NULL,
        'owocowy',
        'Soplica cytrynowa z nutą miodu to wódka smakowa produkowana w Polsce. Doskonała do drinków. Fajny cytrusowy aromat, lekka słodycz. Najlepiej smakuje schłodzona. W wyższych temperaturach dość ostra w smaku.',
        TODO,
        28.0,
        'żółty',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Soplica',
        NULL,
        TODO
        ),
        (
         --5900471007261, region - Polska
        DEFAULT,
        'Soplica Kawowa',
        'likier',
        NULL,
        'inny',
        'Soplica kawowa to polski likier na bazie wódki Soplica. Stworzono ją z myślą o smakoszach małej czarnej, którzy potrafią docenić głębię aromatycznego naparu.  Głęboki smak wyjątkowo aromatycznej kawy połączony ze słodkimi nutami karmelu oraz wanilii oferuje wyraziste i niezapomniane wrażenia. Delikatne, a jednocześnie bardzo wyraziste nuty budzą apetyt na odkrywanie przyjemności w nowej, wysmakowanej odsłonie.',
        TODO,
        25.0,
        'czarny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Soplica',
        NULL,
        TODO
        ),
        (
         --5900471006127, region - Polska
        DEFAULT,
        'Soplica o smaku orzecha w czekoladzie',
        'likier',
        NULL,
        'inny',
        'Aksamitne połączenie smaku wyśmienitej czekolady i aromatycznych orzechów laskowych. Zniewala bogatym aromatem i głębokim, wyrafinowanym smakiem.',
        TODO,
        25.0,
        'czarny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Soplica',
        NULL,
        TODO
        ),
        (
         --5900471006561, region - Polska
        DEFAULT,
        'Soplica Śliwkowa',
        'likier',
        NULL,
        'owocowy',
        'Receptura tej wyjątkowej nalewki oparta jest na owocach śliwek. Jedynie naturalne składniki i staropolskie receptury pozwoliły stworzyć ten szlachetny trunek, zmieniając cierpkie owoce tarniny na słodki bukiet pełen niespotykanych akcentów smakowych i zapachowych. Bogactwa aromatu dopełnia długie leżakowanie w specjalnych warunkach.',
        TODO,
        28.0,
        'fioletowy',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Soplica',
        NULL,
        TODO
        ),
        (
         --5900471006523, region - Polska
        DEFAULT,
        'Soplica Wiśniowa',
        'likier',
        NULL,
        'owocowy',
         'Jedyna w swoim rodzaju nalewka tworzona z w pełni dojrzałych wiśni z polskich sadów. Zgodne ze staropolską tradycją długie leżakowanie trunku oraz wyjątkowa receptura oparta na dojrzewających w słońcu owocach, nadają mu niepowtarzalnego smaku z wyróżniającą się nutą wiśniowej pestki.',
        TODO,
        28.0,
        'czerwony',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Soplica',
        NULL,
        TODO
        ),
               (
         --5900471006165, region - Polska
        DEFAULT,
        'Soplica o smaku wiśni w czekoladzie',
        'likier',
        NULL,
        'inny',
        'Soplica o Smaku Wiśni w Czekoladzie to likier na bazie wódki Soplica. To wyjątkowe połączenie smaku doskonałej czekolady oraz soczystych i pełnych niezwykłego aromatu dojrzewających w słońcu owoców wiśni. Trunek o aksamitnej konsystencji, który przyjemnie pobudza zmysły.',
        TODO,
        25.0,
        'czerwony',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Soplica',
        NULL,
        TODO
        ),