INSERT INTO alcohol
VALUES (
        --barcodes, region dziwne(A)hus - Szwecja
        DEFAULT,
        'Absolut Vodka',
        'wódka',
        NULL,
        'czysta',
        'Odważna, oryginalna i kreatywna. Absolut Vodka zadebiutowała w Nowym Jorku w 1979 roku. Nasza przezroczysta butelka pozbawiona etykiety, inspirowana wyglądem osiemnastowiecznych buteleczek z lekami, wyróżniała się na tle wysokich i krzykliwych produktów konkurencji. W końcu mówimy o Nowym Jorku z lat 70. Trzeba było się wyróżniać, aby być zauważonym. Inspiracja dzięki współpracy. Współpraca między Absolut a artystami i uczonymi była bezprecedensowym wydarzeniem. Po raz pierwszy rozpoczęliśmy współpracę z Andym Warholem w 1985 r. Sukces projektu „Absolut Warhol” zapoczątkował coś w rodzaju sztafety – pałeczka marki Absolut była od tego czasu przekazywana około 550 artystom. W „Spritmuseum” w Sztokholmie znajduje się obecnie ponad 850 dzieł sztuki – warto przyjechać, by je zobaczyć. Reklama na naszych zasadach. W przeciwieństwie do innych marek, które organizują głośne i mało wymyślne kampanie, my postanowiliśmy stworzyć coś subtelnego i powściągliwego, zgodnie z naszymi skandynawskimi korzeniami. Było to połączenie gier słownych w postaci wizualnej lub werbalnej z efektownymi obrazami, ze słynną sylwetką butelki umieszczoną gdzieś na reklamie. Z dumą możemy powiedzieć, że to najdłużej trwająca kampania marketingowa w historii reklamy. Ewolucja, nie rewolucja. Absolut Vodka nieustannie wyróżnia się unikatowym charakterem – zarówno w kwestii wzornictwa, jak i smaku. Zawsze interesujemy się kreatywnością, współpracą i sztuką. I nadal jesteśmy kluczowym składnikiem idealnych drinków na każdą okazję. A jako że wszystkie wódki marki Absolut są produkowane w południowej Szwecji, nasze wspaniałe produkty smakują dziś dokładnie tak samo jak dawniej. Nic się w tej kwestii nie zmieniło.',
        TODO,
        40.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Absolut',
        NULL,
        TODO
        ),
       (
        --barcodes, region - Polska
        DEFAULT,
        'Adam Mickiewicz',
        'wódka',
        NULL,
        'czysta',
        'Wodka Adam Mickiewicz jest symbolem tradycji. W hołdzie wielkiemu Polakowi dedykujemy tak wyjątkowy produkt. Dlatego wódka Adam Mickiewicz nie może zawieźć degustatorów pod żadnym względem. Aby tak się stało, nad całym procesem czuwa wiele osób. Producent BZK ALKO tworzy ją na podstawie receptury inspirowanej XIX wiekiem. Adam Mickiewicz wódka zostaje poddawana wielostopniowej filtracji węglem, przy czym jest wielokrotnie destylowana. Wódka powstała z alkoholu etylowego najwyższej jakości pochodzenia kukurydzianego, czyli zboża pozbawionego glutenu. Dzięki odpowiedniej selekcji surowców bez GMO z certyfikowanych gospodarstw. Drugim rodzajem tego alkoholu jest Adam Mickiewicz leżakowana. Wódka Premium to wyjątkowe połączenie aksamitnie gładkiego smaku. Zamkniętego w smukłej, miedziano-czarnej butelce. Swoją niezwykłość zawdzięcza minimum 7-tygodniowemu leżakowaniu w metalowych zbiornikach. Okresowym mieszaniu, które umożliwiają kontakt z powietrzem i harmonizację płynu. Używany do produkcji wódki najwyższej jakości spirytus jest siedmiokrotnie destylowany. Produkt doskonale nadaje się jako prezent. Jak i na wspólne spotkania okraszone dobrym alkoholem. Zawartość alkoholu: 40%',
        TODO,
        40.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Adam Mickiewicz',
        NULL,
        TODO
        ),
        (
         --barcodes, region - Polska
        DEFAULT,
        'Amundsen',
        'wódka',
        NULL,
        'czysta',
         'Amundsen Vodka została stworzona, by uhonorować jedną z największych ekspedycji w historii XX wieku – zdobycie Bieguna Południowego w 1911 roku. Wódka czysta top premium zamknięta w designerskiej butelce, która swoim wyglądem do złudzenia przypomina bryłę lodowca, podawana schłodzona do temperatury 0 stopni Celsjusza, odsłania swój niepowtarzalny delikatny smak. Jest on efektem połączenia unikalnych składników, krystalicznie czystej wody oraz powolnego procesu rektyfikacji.',
        TODO,
        40.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'below 0',
        'Amundsen',
        NULL,
        TODO
        ),
        (
        --flavour - pigwa, barcodes, region - Polska,
        DEFAULT,
        'Barmańska Pigwa',
        'wódka',
        NULL,
        'smakowa',
        'Inspiracją do powstania Barmańskiej był smak dojrzałych soczystych owoców. Dzięki temu powstała receptura z udziałem soku z pigwy, która sprawia, że Barmańska zaskakuje owocową świeżością. Wyjątkowe walory wynikają z idealnie dobranych proporcji alkoholu i pigwowego smaku. Najlepiej podawać schłodzoną lub z kostkami lodu.',
        TODO,
        21.0,
        'pomarańczowy',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Barmańska',
        NULL,
        TODO
        ),
        (
        --flavour - wiśnia, barcodes, region - Polska
        DEFAULT,
        'Barmańska Wiśnia',
        'wódka',
        NULL,
        'smakowa',
        'Barmańska Wiśnia to Polska wódka smakowa. Inspiracją do powstania Barmańskiej był smak dojrzałych, soczystych owoców. Dzięki temu powstała receptura z udziałem soku z wiśni, która sprawia, że Barmańska zaskakuje owocową świeżością. Wyjątkowe walory wynikają również z idealnie dobranych proporcji alkoholu i wiśniowego smaku.Najlepiej podawać schłodzoną lub z kostkami lodu.',
        TODO,
        21.0,
        'czerwony',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Barmańska',
        NULL,
        TODO
        ),
        (
        --barcodes, region - Wielkopolskie Polska
        DEFAULT,
        'Biały Bocian',
        'wódka',
        NULL,
        'czysta',
         'Biały Bocian to Polska wódka wódka premium. Posiada unikalny zestaw składników, dzięki czemu jest oryginalna i wyrafinowana. Jest to typ wódki Gluten Free. Pochodzi z wielkopolskich zbóż, każdy składnik jest dobrze dopracowany, dzięki czemu posiada tak wyrazisty smak. Jest delikatna i subtelna.',
        TODO,
        40.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Biały Bocian',
        NULL,
        TODO
        ),
        (
        --barcodes, region Polska
        DEFAULT,
        'Bols', --Holenderska marka wódki produkowana w polsce
        'wódka',
        NULL,
        'czysta',
        'Czysta wódka produkowana z wykorzystaniem nowatorskich metod- w procesie rektyfikacji wykorzystuje się unikatową hydroselekcję, pozwalającą uzyskać spirytus o charakterze neutralnego, poddawanego następnie wielokrotnej filtracji i uszlachetnianiu, sam zaś spirytus jest wytwarzany u producentów spełniających wysokie wymagania technologiczne - pod stałą kontrolą i nadzorem jakości firmy Bols. Bols to holenderska marka wódki, istniejąca od 1575 r. co upamiętnia herb na etykiecie alkoholu. W Polsce produkowana jest od 1994 r. Wódka Bols została wyróżniona w 2010 r. prestiżowym tytułem "Wyjątkowej" przez Jury International Taste & Quality Institute- w konkursie Superior Taste Award alkohole analizowane były między innymi pod względem pierwszego wrażenia, smaku i zapachu. We wszystkich tych kategoriach otrzymała bardzo wysokie noty, co zaowocowało przyznaniem BOLS Premium Vodka najwyższej nagrody trzech gwiazdek, uzyskując miano "Exceptional - Wyjątkowej". Formuła testu zakłada degustację produktów bez ich identyfikacji z marką czy opakowaniem, przez wieloosobową, międzynarodową komisję, co pozwala potwierdzić rzeczywistą jakość trunku bez wpływów marki. Wszystkie warianty wódki BOLS produkowane są w jednym z najnowocześniejszych zakładów rektyfikacyjnych na świecie w Obornikach Wielkopolskich.Wódka jest tam poddawana 4-krotnemu procesowi destylacji oraz filtracji węglowo-miedziowej, dzięki temu jej czystość przewyższa aż 5-krotnie restrykcyjne unijne normy. To sprawia, że ma niezwykle łagodny smak i zapach, pozostawiając na podniebieniu wyczuwalną esencję wódki najwyższej jakości.',
        TODO,
        40.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Bols',
        NULL,
        TODO
        ),
        (
        --barcodes, region Podlasie Polska
        DEFAULT,
        'Chopin',
        'wódka',
        NULL,
        'czysta',
        'Chopin Rye to wódka wywodząca się z polskiego Podlasia. Wytwarzana jest w legendarnym Polmosie Siedlce z najwyższej jakości żyta. Proces wytwarzania wódki Chopin jest bardzo podobny do metod stosowanych przed laty. Wódka nie zawiera żadnych dodatków, a jej sekret tkwi w prostocie produkcji oraz odpowiedniej selekcji składników. Chopin Rye charakteryzuje się delikatnym choć bogatym i zrównoważonym smakiem z odrobinę pikantnym finiszem oraz wyraźnym aromatem żytniego chleba z lekko surową nutą. ',
        TODO,
        40.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Chopin',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Uusimaa, Finlandia
        DEFAULT,
        'Finlandia',
        'wódka',
        NULL,
        'czysta',
        'Wódka Finlandia jest produkowana z uprawianego w Finlandii sześciorzędowego jęczmienia i czystej wody źródlanej z lodowca. Woda jest naturalnie filtrowana przez moreny, pozostałe po zejściu lodowca tysiące lat temu, dlatego wódka nie potrzebuje żadnej filtracji, ani innego sztucznego oczyszczania — w przeciwieństwie do niektórych innych wódek. Składniki te nadają wódce wytrawny, lekki i gładki smak oraz delikatny aromat.',
        TODO,
        40.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Finlandia Botanical',
        'wódka',
         NULL,
        'czysta',
        'Finlandia Vodka to wódka z najlepszego fińskiego jęczmienia, dojrzewającego w promieniach słońca północy i krystalicznie czystej wody z polodowcowego źródła. W nowoczesnym procesie destylacji powstaje wódka o czystym, delikatnym smaku, idealnie pasująca do koktajli, picia w shotach lub na lodzie.',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Ukraina
        DEFAULT,
        'Hlibny Dar Classic',
        'wódka',
        NULL,
        'czysta',
        'Hlibny Dar to nieskazitelna ukraińska wódka, wódka jest uznawana w światowych rankingach, ma wiele renomowanych nagród i słusznie zajmuje miejsce w pierwszej trójce. Wykonana jest wyłącznie z naturalnych składników, wysokiej jakości alkoholi klasy „Lux”, na ekologicznie czystej wodzie ze studni artezyjskiej. Diamentową przezroczystość napoju zapewniają liczne etapy technologii czyszczenia nowej generacji. To jest wybór ludzi zmieniających ten świat. Przez ponad 10 lat z rzędu Hlebniy Dar uosabia nienaganną jakość.',
        TODO,
        40.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Hlibny Dar',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Polska
        DEFAULT,
        'Krupnik',
        'wódka',
        NULL,
        'czysta',
         'Krupnik wódka stanowi idealne połączenie polskiej tradycji i kunsztu nowoczesnej destylacji. Inspirowani legendarną recepturą wytwarzamy wódkę najwyższej jakości o wyjątkowo łagodnym smaku i aromacie.',
        TODO,
        40.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Krupnik',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Polska, flavour cytryna
        DEFAULT,
        'Krupnik Cytryna',
        'likier',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),
               (
        --barcodes, region -Uusimaa, Finlandia, flavour ogórek mięta
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
         '',
        TODO,
        30.0,
        'bezbarwne',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),


