INSERT INTO alcohol
VALUES (
        --barcodes, region dziwne(A)hus - Szwecja
        DEFAULT,
        'Absolut Vodka',
        'wódka',
        NULL,
        'czysta',
        'Odważna, oryginalna i kreatywna. Absolut Vodka zadebiutowała w Nowym Jorku w 1979 roku. Nasza przezroczysta butelka pozbawiona etykiety, inspirowana wyglądem osiemnastowiecznych buteleczek z lekami, wyróżniała się na tle wysokich i krzykliwych produktów konkurencji. W końcu mówimy o Nowym Jorku z lat 70. Trzeba było się wyróżniać, aby być zauważonym. Inspiracja dzięki współpracy. Współpraca między Absolut a artystami i uczonymi była bezprecedensowym wydarzeniem. Po raz pierwszy rozpoczęliśmy współpracę z Andym Warholem w 1985 r. Sukces projektu „Absolut Warhol” zapoczątkował coś w rodzaju sztafety – pałeczka marki Absolut była od tego czasu przekazywana około 550 artystom. W „Spritmuseum” w Sztokholmie znajduje się obecnie ponad 850 dzieł sztuki – warto przyjechać, by je zobaczyć. Reklama na naszych zasadach. W przeciwieństwie do innych marek, które organizują głośne i mało wymyślne kampanie, my postanowiliśmy stworzyć coś subtelnego i powściągliwego, zgodnie z naszymi skandynawskimi korzeniami. Było to połączenie gier słownych w postaci wizualnej lub werbalnej z efektownymi obrazami, ze słynną sylwetką butelki umieszczoną gdzieś na reklamie. Z dumą możemy powiedzieć, że to najdłużej trwająca kampania marketingowa w historii reklamy. Ewolucja, nie rewolucja. Absolut Vodka nieustannie wyróżnia się unikatowym charakterem – zarówno w kwestii wzornictwa, jak i smaku. Zawsze interesujemy się kreatywnością, współpracą i sztuką. I nadal jesteśmy kluczowym składnikiem idealnych drinków na każdą okazję. A jako że wszystkie wódki marki Absolut są produkowane w południowej Szwecji, nasze wspaniałe produkty smakują dziś dokładnie tak samo jak dawniej. Nic się w tej kwestii nie zmieniło.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Absolut',
        NULL,
        TODO
        ),
        (
        --barcodes, region - Polska
        DEFAULT,
        'Adam Mickiewicz',
        'wódka',
        NULL,
        'czysta',
        'Wodka Adam Mickiewicz jest symbolem tradycji. W hołdzie wielkiemu Polakowi dedykujemy tak wyjątkowy produkt. Dlatego wódka Adam Mickiewicz nie może zawieźć degustatorów pod żadnym względem. Aby tak się stało, nad całym procesem czuwa wiele osób. Producent BZK ALKO tworzy ją na podstawie receptury inspirowanej XIX wiekiem. Adam Mickiewicz wódka zostaje poddawana wielostopniowej filtracji węglem, przy czym jest wielokrotnie destylowana. Wódka powstała z alkoholu etylowego najwyższej jakości pochodzenia kukurydzianego, czyli zboża pozbawionego glutenu. Dzięki odpowiedniej selekcji surowców bez GMO z certyfikowanych gospodarstw. Drugim rodzajem tego alkoholu jest Adam Mickiewicz leżakowana. Wódka Premium to wyjątkowe połączenie aksamitnie gładkiego smaku. Zamkniętego w smukłej, miedziano-czarnej butelce. Swoją niezwykłość zawdzięcza minimum 7-tygodniowemu leżakowaniu w metalowych zbiornikach. Okresowym mieszaniu, które umożliwiają kontakt z powietrzem i harmonizację płynu. Używany do produkcji wódki najwyższej jakości spirytus jest siedmiokrotnie destylowany. Produkt doskonale nadaje się jako prezent. Jak i na wspólne spotkania okraszone dobrym alkoholem. Zawartość alkoholu: 40%',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Adam Mickiewicz',
        NULL,
        TODO
        ),
        (
         --barcodes, region - Polska
        DEFAULT,
        'Amundsen',
        'wódka',
        NULL,
        'czysta',
         'Amundsen Vodka została stworzona, by uhonorować jedną z największych ekspedycji w historii XX wieku – zdobycie Bieguna Południowego w 1911 roku. Wódka czysta top premium zamknięta w designerskiej butelce, która swoim wyglądem do złudzenia przypomina bryłę lodowca, podawana schłodzona do temperatury 0 stopni Celsjusza, odsłania swój niepowtarzalny delikatny smak. Jest on efektem połączenia unikalnych składników, krystalicznie czystej wody oraz powolnego procesu rektyfikacji.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'below 0',
        'Amundsen',
        NULL,
        TODO
        ),
        (
        --barcodes, region - Wielkopolskie Polska
        DEFAULT,
        'Biały Bocian',
        'wódka',
        NULL,
        'czysta',
         'Biały Bocian to Polska wódka wódka premium. Posiada unikalny zestaw składników, dzięki czemu jest oryginalna i wyrafinowana. Jest to typ wódki Gluten Free. Pochodzi z wielkopolskich zbóż, każdy składnik jest dobrze dopracowany, dzięki czemu posiada tak wyrazisty smak. Jest delikatna i subtelna.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Biały Bocian',
        NULL,
        TODO
        ),
        (
        --barcodes, region Polska
        DEFAULT,
        'Bols', --Holenderska marka wódki produkowana w polsce
        'wódka',
        NULL,
        'czysta',
        'Czysta wódka produkowana z wykorzystaniem nowatorskich metod- w procesie rektyfikacji wykorzystuje się unikatową hydroselekcję, pozwalającą uzyskać spirytus o charakterze neutralnego, poddawanego następnie wielokrotnej filtracji i uszlachetnianiu, sam zaś spirytus jest wytwarzany u producentów spełniających wysokie wymagania technologiczne - pod stałą kontrolą i nadzorem jakości firmy Bols. Bols to holenderska marka wódki, istniejąca od 1575 r. co upamiętnia herb na etykiecie alkoholu. W Polsce produkowana jest od 1994 r. Wódka Bols została wyróżniona w 2010 r. prestiżowym tytułem "Wyjątkowej" przez Jury International Taste & Quality Institute- w konkursie Superior Taste Award alkohole analizowane były między innymi pod względem pierwszego wrażenia, smaku i zapachu. We wszystkich tych kategoriach otrzymała bardzo wysokie noty, co zaowocowało przyznaniem BOLS Premium Vodka najwyższej nagrody trzech gwiazdek, uzyskując miano "Exceptional - Wyjątkowej". Formuła testu zakłada degustację produktów bez ich identyfikacji z marką czy opakowaniem, przez wieloosobową, międzynarodową komisję, co pozwala potwierdzić rzeczywistą jakość trunku bez wpływów marki. Wszystkie warianty wódki BOLS produkowane są w jednym z najnowocześniejszych zakładów rektyfikacyjnych na świecie w Obornikach Wielkopolskich.Wódka jest tam poddawana 4-krotnemu procesowi destylacji oraz filtracji węglowo-miedziowej, dzięki temu jej czystość przewyższa aż 5-krotnie restrykcyjne unijne normy. To sprawia, że ma niezwykle łagodny smak i zapach, pozostawiając na podniebieniu wyczuwalną esencję wódki najwyższej jakości.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Bols',
        NULL,
        TODO
        ),
        (
        --barcodes, region Podlasie Polska
        DEFAULT,
        'Chopin',
        'wódka',
        NULL,
        'czysta',
        'Chopin Rye to wódka wywodząca się z polskiego Podlasia. Wytwarzana jest w legendarnym Polmosie Siedlce z najwyższej jakości żyta. Proces wytwarzania wódki Chopin jest bardzo podobny do metod stosowanych przed laty. Wódka nie zawiera żadnych dodatków, a jej sekret tkwi w prostocie produkcji oraz odpowiedniej selekcji składników. Chopin Rye charakteryzuje się delikatnym choć bogatym i zrównoważonym smakiem z odrobinę pikantnym finiszem oraz wyraźnym aromatem żytniego chleba z lekko surową nutą. ',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Chopin',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Uusimaa, Finlandia
        DEFAULT,
        'Finlandia',
        'wódka',
        NULL,
        'czysta',
        'Wódka Finlandia jest produkowana z uprawianego w Finlandii sześciorzędowego jęczmienia i czystej wody źródlanej z lodowca. Woda jest naturalnie filtrowana przez moreny, pozostałe po zejściu lodowca tysiące lat temu, dlatego wódka nie potrzebuje żadnej filtracji, ani innego sztucznego oczyszczania — w przeciwieństwie do niektórych innych wódek. Składniki te nadają wódce wytrawny, lekki i gładki smak oraz delikatny aromat.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Finlandia',
        NULL,
        TODO
        ),

        (
        --barcodes, region -Ukraina
        DEFAULT,
        'Hlibny Dar Classic',
        'wódka',
        NULL,
        'czysta',
        'Hlibny Dar to nieskazitelna ukraińska wódka, wódka jest uznawana w światowych rankingach, ma wiele renomowanych nagród i słusznie zajmuje miejsce w pierwszej trójce. Wykonana jest wyłącznie z naturalnych składników, wysokiej jakości alkoholi klasy „Lux”, na ekologicznie czystej wodzie ze studni artezyjskiej. Diamentową przezroczystość napoju zapewniają liczne etapy technologii czyszczenia nowej generacji. To jest wybór ludzi zmieniających ten świat. Przez ponad 10 lat z rzędu Hlebniy Dar uosabia nienaganną jakość.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Hlibny Dar',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Polska
        DEFAULT,
        'Krupnik',
        'wódka',
        NULL,
        'czysta',
         'Krupnik wódka stanowi idealne połączenie polskiej tradycji i kunsztu nowoczesnej destylacji. Inspirowani legendarną recepturą wytwarzamy wódkę najwyższej jakości o wyjątkowo łagodnym smaku i aromacie.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Krupnik',
        NULL,
        TODO
        ),
        (
        --barcodes, region -Ukraina
        DEFAULT,
        'Hlibny Dar',
        'wódka',
        NULL,
        'czysta',
        'Hlibny Dar to nieskazitelna ukraińska wódka, wódka jest uznawana w światowych rankingach, ma wiele renomowanych nagród i słusznie zajmuje miejsce w pierwszej trójce. Wykonana jest wyłącznie z naturalnych składników, wysokiej jakości alkoholi klasy „Lux”, na ekologicznie czystej wodzie ze studni artezyjskiej. Diamentową przezroczystość napoju zapewniają liczne etapy technologii czyszczenia nowej generacji. To jest wybór ludzi zmieniających ten świat. Przez ponad 10 lat z rzędu Hlebniy Dar uosabia nienaganną jakość.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Hlibny Dar',
        NULL,
        TODO
        ),
        (
        --barcodes, region - Polska
        DEFAULT,
        'Luksusowa',
        'wódka',
        NULL,
        'czysta',
         'Luksusowa to wódka wyprodukowana z ziemniaków wyróżniająca się na rynku zdominowanym przez wódki zbożowe. Swój niepowtarzalny charakter zawdzięcza doświadczeniu naszych gorzelników oraz wyłącznie polskim ziemniakom. Jej process produkcji jest dużo bardziej skomplikowany i kosztowny niż wódek zbożowych, ale warto - łagodny, pełny smak zadowoli każdego znawcę tematu.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Luksusowa',
        NULL,
        TODO
        ),
        (
        --barcodes, region - Ukraina
        DEFAULT,
        'Nemiroff Original',
        'wódka',
        NULL,
        'czysta',
         'Namiroff Original to Ukraińska wódka produkowana w tradycyjny sposób z najlepszych ziaren pszenicy. Spodoba się osobom, które lubią zdecydowany i wyrazisty smak. Często jest określana mianem męskiej wódki, lecz posmak kminku i miodu, pozostający w ustach na długo, doceni nawet płeć piękna. Nemiroff Original nie potrzebuje towarzystwa, dzięki harmonijnej kompozycji doskonale smakuje solo, a drinkom nada elegancji i głębi. To wódka, którą naprawdę trudno zapomnieć.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Nemiroff',
        NULL,
        TODO
        ),
        (
        --barcodes, region - Polska
        DEFAULT,
        'Ogiński',
        'wódka',
        NULL,
        'czysta',
        'Ogiński Vodka to wybitnie czysta wódka bezglutenowa, tworzona w rytm zasad perfect composition. Każde ziarno dobieramy zgodnie z jej regułami, tak by dały najwyższej jakości spirytus, który harmonijnie łączy się z krystalicznie czystą wodą. To mistrzowskie zestawienie, wirtuozersko zinterpretowane w procesie wielostopniowej filtracji zyskuje unikalny, neutralny smak i wymiar wyjątkowego dzieła.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Ogiński',
        NULL,
        TODO
        ),
               (
        --barcodes, region - Polska
        DEFAULT,
        'Ostoya',
        'wódka',
        NULL,
        'czysta',
        'Krystalicznnie czyste źródła, falujące trawy płonin, unikalny bieszczadzki mikroklimat. To tu, bez pośpiechu, w rytmie nadanym przez naturę, dojrzewa szlachetna pszenica, z której wytwarzana jest wódka OSTOYA. Delektuj się jej jedwabiście gładkim smakiem.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Ostoya',
        NULL,
        TODO
        ),
        (
        --barcodes, region - Polska
        DEFAULT,
        'Pan Tadeusz',
        'wódka',
        NULL,
        'czysta',
        'Polska wódka wytwarzana ze spirytusu zbożowego, pozyskiwanego z najlepszego według nas żyta i pszenicy. Łączy w sobię tradycję i współczesność, łagodność i wyrazistość. Dzięki niezwykle starannemu procesowi doboru proporcji składników i destylacji, stworzyliśmy wódkę, która naszym zdaniem spełnia najwyższe wymagania jakościowe i smakowe.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Pan Tadeusz',
        NULL,
        TODO
        ),
        (
         --barcodes, region -Polska
        DEFAULT,
        'Parkowa',
        'wódka',
        NULL,
        'czysta',
         'Wódka czysta zbożowa. Wyprodukowano w Polsce dla Jeronimo Martins Polska S.A.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Parkowa',
        NULL,
        TODO
        ),
               (
         --5907377003090, region - Polska
        DEFAULT,
        'Toruńska Ziemniaczana ',
        'wódka',
        NULL,
        'czysta',
         'Wódka Toruńska Ziemniaczana to wódka z najszlachetniejszego ziemniaczanego spirytusu z wyłącznie polskich ziemniaków. To wódka, która osiaga poziom rzemieślniczych wódek ziemniaczanych klasy premium, takich jak np. Młody Ziemniak, jednocześnie pozostając w przystępnym przedziale cenowym. Butelka stylizowana na lata dwudzieste jest dodatkowym atutem.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Toruńska',
        NULL,
        TODO
        ),
               (
         --5902573004278, region - Polska
        DEFAULT,
        'Żołądkowa de Luxe',
        'wódka',
        NULL,
        'czysta',
        'Żołądkowa de Luxe otrzymała wiele prestiżowych międzynarodowych nagród za smak, m.in. złoty medal w konkursie Monde Selection w Brukseli w 2014 roku i dwie złote gwiazdki z International Taste & Quality Institute (iTQi), również w 2014 roku. Otrzymała również srebro w konkursie International Spirits Challenge 2015.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Żołądkowa',
        NULL,
        TODO
        ),
               (
         --5900343001915, region - Polska
        DEFAULT,
        'Żubrówka Biała',
        'wódka',
        NULL,
        'czysta',
        'Żubrówka Biała to krystalicznie czysta wersja cenionej na całym świecie Żubrówki. Dzięki naturalnemu pochodzeniu oraz zastosowaniu najnowszych technologii, produkt ten cechuje się nieskazitelną czystością i łagodnym smakiem.',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Żubrówka',
        NULL,
        TODO
        ),
               (
         --5900343005272, region - Podlasie, Polska
        DEFAULT,
        'Żubrówka Bison Grass',
        'wódka',
        NULL,
        'smakowa',
         'Żubrówka Bison Grass to wódka ziołowa z Niziny Północnopodlaskiej aromatyzowana ekstraktem z trawy żubrowej.',
        TODO,
        37.5,
        'NULL', --ciężko powiedzieć
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Żubrówka',
        NULL,
        TODO
        ),
        (
         --5900343010405, region -Polska
        DEFAULT,
        'Żytniówka',
        'wódka',
        NULL,
        'czysta',
         'Żytniówka to klasyczny wariant znanej i popularnej marki Żytniówka, wyprodukowany z polskiego żytniego spirytusu. W smaku słodkawa z lekką dymną nutą.',
        TODO,
        38.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Żytniówka',
        NULL,
        TODO
        ),
       --end--
        (
        --barcodes, region -
        DEFAULT,
        'nazwa',
        'wódka',
        NULL,
        'czysta',
         'opis',
        TODO,
        40.0,
        'bezbarwny',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'brand',
        NULL,
        TODO
        ),


